/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface KeyframedAudioPlayer {
    'name': string;
    'url': string;
  }
}

declare global {


  interface HTMLKeyframedAudioPlayerElement extends Components.KeyframedAudioPlayer, HTMLStencilElement {}
  var HTMLKeyframedAudioPlayerElement: {
    prototype: HTMLKeyframedAudioPlayerElement;
    new (): HTMLKeyframedAudioPlayerElement;
  };
  interface HTMLElementTagNameMap {
    'keyframed-audio-player': HTMLKeyframedAudioPlayerElement;
  }
}

declare namespace LocalJSX {
  interface KeyframedAudioPlayer extends JSXBase.HTMLAttributes<HTMLKeyframedAudioPlayerElement> {
    'name'?: string;
    'url'?: string;
  }

  interface IntrinsicElements {
    'keyframed-audio-player': KeyframedAudioPlayer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


